export const ROLES = {
    ADMIN: "admin",
    DRIVER: "driver"
}
export const ALL_PERMISSIONS = {
    CREATE_ORDER: "create_order",
    VIEW_ORDER_DETAILS: "view_order_detail",
    EDIT_ORDER: "edit_order",
    DELETE_ORDER: "delete_order",
    VIEW_ALL_ORDERS: "view_all_orders",
    CANCEL_ORDER: "cancel_order",
    ASSIGN_ORDER: "assign_order",
    MARK_DELIVERED: "mark_order_delivered",
    PICKUP_ORDER: "pickup_order"
}
export const PERMISSIONS = {
    [ROLES.ADMIN]: [ALL_PERMISSIONS.CREATE_ORDER, ALL_PERMISSIONS.EDIT_ORDER, ALL_PERMISSIONS.DELETE_ORDER, ALL_PERMISSIONS.ASSIGN_ORDER, ALL_PERMISSIONS.CANCEL_ORDER, ALL_PERMISSIONS.MARK_DELIVERED, ALL_PERMISSIONS.VIEW_ALL_ORDERS, ALL_PERMISSIONS.VIEW_ORDER_DETAILS],
    [ROLES.DRIVER] : [ALL_PERMISSIONS.VIEW_ALL_ORDERS, ALL_PERMISSIONS.MARK_DELIVERED, ALL_PERMISSIONS.PICKUP_ORDER, ALL_PERMISSIONS.VIEW_ORDER_DETAILS, ALL_PERMISSIONS.CANCEL_ORDER]

}